-- CONSTRAINTS FOR PATS DATABASE
--
-- by Byungjoon Yoon & Leo Ying
--
--

-- FOREIGN KEY AND OTHER CONSTRAINTS

--UNSURE HOW TO HANDLE THIS>....
ALTER TABLE medicines ADD CHECK (method IN ('injection','oral','intravenous'));

ALTER TABLE pets ADD FOREIGN KEY (animal_id) REFERENCES animals ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE pets ADD FOREIGN KEY (owner_id) REFERENCES owners ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE visits ADD FOREIGN KEY (pet_id) REFERENCES pets ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE medicine_costs ADD FOREIGN KEY (medicine_id) REFERENCES medicines ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE animal_medicines ADD FOREIGN KEY (animal_id) REFERENCES animals ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE animal_medicines ADD FOREIGN KEY (medicine_id) REFERENCES medicines ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE visit_medicines ADD FOREIGN KEY (visit_id) REFERENCES visits ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE visit_medicines ADD FOREIGN KEY (medicine_id) REFERENCES medicines ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE treatments ADD FOREIGN KEY (visit_id) REFERENCES visits ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE treatments ADD FOREIGN KEY (procedure_id) REFERENCES procedures ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE procedure_costs ADD FOREIGN KEY (procedure_id) REFERENCES procedures ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE notes ADD FOREIGN KEY (user_id) REFERENCES users ON DELETE RESTRICT ON UPDATE CASCADE;
